name: Python CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lint with flake8
        run: |
          # Linting commands with flake8
          # Replace this comment with actual linting commands using flake8

      - name: Test with pytest
        run: |
          pytest  # Ejecutar pruebas pytest

      - name: Build and Push in Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: cataluniat1/django1
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Connect to ssh and pull docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull cataluniat1/django1:latest
            sudo docker-compose -f /home/ubuntu/app/docker-compose.yml up -d
